# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 197e7a33c433ce14ae05db79d8e0bc7992f5c13297d1832074670960601dfe2173529ec0c9a3cd0e84a03cff0859dd577fcff0d14d20bbe101617a5f0f1ac9f4

test:
  secret_key_base: 41cbf16124d12d14d84cd32f6ba5d8dc65045e04101d4c3773d0b8956071af8531bb6f6b25e273356bab78865ecdef3d322dd4a4f397db6731a8cf7877309c0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
